name: switchfootcreative
favicon: null
layout_spectrum: 0.5019
typography_spectrum: 0.50317
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#07476a'
    - '#000000'
    - '#b7aa2c'
    - '#ffff00'
    - '#7f7f00'
  brandStrength: 0.6146081101614982
  lightness: 0.375
  saturation: 0.4375
  rhythmicContrast: 0.25
purpose: []
